In [1]:
import pandas as pd
import json

In [13]:
df = pd.read_csv('Data_Penduduk_NusantaraLens.csv', skiprows=1)
display(df)

                Daerah  Laki-laki  Perempuan      Total  Unnamed: 4
0                 Aceh  2.825.512  2.800.448  5.625.960         NaN
1           Yogyakarta  1.870.100  1.911.400  3.781.600         NaN
2  Nusa Tenggara Timur  2.871.300  2.871.300  5.742.600         NaN

In [17]:
df_clean =  df.loc[:, ~df.columns.str.contains('^Unnamed')]
display(df_clean)

df_clean.to_csv('Data_Penduduk.csv')
df_clean.to_json('Data_Penduduk.json')

                Daerah  Laki-laki  Perempuan      Total
0                 Aceh  2.825.512  2.800.448  5.625.960
1           Yogyakarta  1.870.100  1.911.400  3.781.600
2  Nusa Tenggara Timur  2.871.300  2.871.300  5.742.600