In [ ]:
import pandas as pd

In [2]:
df = pd.read_excel(
    "Jumlah Penduduk NTT.xlsx",
    sheet_name="Data 1",
    header=[1, 2]
)
display(df)
print("=="*20)
display(df.info())

      Unnamed: 0_level_0 Laki-Laki                                      \
      Unnamed: 0_level_1      2021     2022     2023     2024     2025
0            Sumba Barat     75374    76665    77964    79244    80527
1            Sumba Timur    127411   129256   131082   132894   134682
2                 Kupang    187326   189157   190886   192506   194020
3   Timor Tengah Selatan    228892   232196   235486   238756   242011
4     Timor Tengah Utara    131897   133982   136088   138215   140357
5                   Belu    111080   113370   115654   117944   120216
6                   Alor    106060   107840   109620   111413   113203
7                Lembata     66333    67379    68409    69432    70452
8           Flores Timur    137425   139568   141738   143923   146119
9                  Sikka    157859   160447   163060   165690   168336
10                  Ende    133682   135108   136536   137961   139390
11                 Ngada     82485    83614    84763    85909    87071
12             Manggarai    158672   161539   164420   167306   170185
13             Rote Ndao     73356    74559    75766    76968    78172
14       Manggarai Barat    131171   133666   136188   138748   141320
15          Sumba Tengah     44575    45501    46420    47349    48274
16      Sumba Barat Daya    158242   161519   164825   168155   171513
17               Nagekeo     79808    80924    82059    83187    84334
18       Manggarai Timur    141622   144335   147041   149733   152406
19           Sabu Raijua     46146    46845    47553    48267    48972
20                Malaka     91990    93184    94380    95589    96794
21           Kota Kupang    226562   230809   234963   238997   242903
22   Nusa Tenggara Timur   2697968  2741463  2784901  2828186  2871257

            Perempuan
       2026      2021     2022     2023     2024     2025     2026
0     81800     71834    73139    74450    75769    77068    78370
1    136454    120458   122446   124416   126367   128293   130201
2    195430    182161   184102   185951   187706   189367   190923
3    245253    232008   235536   239035   242525   245988   249439
4    142517    131159   133164   135189   137224   139280   141338
5    122480    110525   112937   115354   117765   120176   122574
6    114993    108515   110219   111916   113607   115301   116977
7     71473     71136    72057    72982    73913    74819    75729
8    148309    142557   144554   146572   148600   150641   152688
9    171009    167678   169982   172300   174637   176983   179334
10   140793    139291   140677   142045   143410   144775   146118
11    88229     84587    85769    86973    88179    89391    90614
12   173055    158690   161515   164338   167158   169968   172771
13    79377     72305    73525    74755    75982    77199    78411
14   143916    129206   131947   134729   137536   140372   143226
15    49206     42305    43205    44101    45005    45913    46830
16   174894    150567   153908   157248   160616   163987   167393
17    85472     81670    82821    84004    85168    86335    87502
18   155058    138304   141039   143749   146441   149119   151780
19    49686     44305    45032    45777    46520    47287    48054
20    97988     94016    95309    96614    97921    99214   100508
21   246669    223135   227444   231669   235804   239831   243724
22  2914061   2696412  2740327  2784167  2827853  2871307  2914504

========================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 13 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   (Unnamed: 0_level_0, Unnamed: 0_level_1)  23 non-null     object
 1   (Laki-Laki, 2021)                         23 non-null     int64
 2   (Laki-Laki, 2022)                         23 non-null     int64
 3   (Laki-Laki, 2023)                         23 non-null     int64
 4   (Laki-Laki, 2024)                         23 non-null     int64
 5   (Laki-Laki, 2025)                         23 non-null     int64
 6   (Laki-Laki, 2026)                         23 non-null     int64
 7   (Perempuan, 2021)                         23 non-null     int64
 8   (Perempuan, 2022)                         23 non-null     int64
 9   (Perempuan, 2023)                         23 non-null     int64
 10  (Perempuan, 2024)                         23 non-null     int64
 11  (Perempuan, 2025)                         23 non-null     int64
 12  (Perempuan, 2026)                         23 non-null     int64
dtypes: int64(12), object(1)
memory usage: 2.5+ KB

None

In [4]:
df.drop(index=[22], inplace=True)
display(df)

      Unnamed: 0_level_0 Laki-Laki                                          \
      Unnamed: 0_level_1      2021    2022    2023    2024    2025    2026
0            Sumba Barat     75374   76665   77964   79244   80527   81800
1            Sumba Timur    127411  129256  131082  132894  134682  136454
2                 Kupang    187326  189157  190886  192506  194020  195430
3   Timor Tengah Selatan    228892  232196  235486  238756  242011  245253
4     Timor Tengah Utara    131897  133982  136088  138215  140357  142517
5                   Belu    111080  113370  115654  117944  120216  122480
6                   Alor    106060  107840  109620  111413  113203  114993
7                Lembata     66333   67379   68409   69432   70452   71473
8           Flores Timur    137425  139568  141738  143923  146119  148309
9                  Sikka    157859  160447  163060  165690  168336  171009
10                  Ende    133682  135108  136536  137961  139390  140793
11                 Ngada     82485   83614   84763   85909   87071   88229
12             Manggarai    158672  161539  164420  167306  170185  173055
13             Rote Ndao     73356   74559   75766   76968   78172   79377
14       Manggarai Barat    131171  133666  136188  138748  141320  143916
15          Sumba Tengah     44575   45501   46420   47349   48274   49206
16      Sumba Barat Daya    158242  161519  164825  168155  171513  174894
17               Nagekeo     79808   80924   82059   83187   84334   85472
18       Manggarai Timur    141622  144335  147041  149733  152406  155058
19           Sabu Raijua     46146   46845   47553   48267   48972   49686
20                Malaka     91990   93184   94380   95589   96794   97988
21           Kota Kupang    226562  230809  234963  238997  242903  246669

   Perempuan
        2021    2022    2023    2024    2025    2026
0      71834   73139   74450   75769   77068   78370
1     120458  122446  124416  126367  128293  130201
2     182161  184102  185951  187706  189367  190923
3     232008  235536  239035  242525  245988  249439
4     131159  133164  135189  137224  139280  141338
5     110525  112937  115354  117765  120176  122574
6     108515  110219  111916  113607  115301  116977
7      71136   72057   72982   73913   74819   75729
8     142557  144554  146572  148600  150641  152688
9     167678  169982  172300  174637  176983  179334
10    139291  140677  142045  143410  144775  146118
11     84587   85769   86973   88179   89391   90614
12    158690  161515  164338  167158  169968  172771
13     72305   73525   74755   75982   77199   78411
14    129206  131947  134729  137536  140372  143226
15     42305   43205   44101   45005   45913   46830
16    150567  153908  157248  160616  163987  167393
17     81670   82821   84004   85168   86335   87502
18    138304  141039  143749  146441  149119  151780
19     44305   45032   45777   46520   47287   48054
20     94016   95309   96614   97921   99214  100508
21    223135  227444  231669  235804  239831  243724

In [3]:
df_umur = df.iloc[0:22]
total_laki = df_umur.iloc[:, 1:7].sum().values
total_perempuan = df_umur.iloc[:, 7:13].sum().values
df_ringkasan = pd.DataFrame({
    'Tahun': ['2021', '2022', '2023', '2024', '2025', '2026'],
    'Laki-Laki': total_laki,
    'Perempuan': total_perempuan
})

display(df_ringkasan)
df_ringkasan.to_csv('Jumlah Penduduk NTT.csv', index=False)

  Tahun  Laki-Laki  Perempuan
0  2021    2697968    2696412
1  2022    2741463    2740327
2  2023    2784901    2784167
3  2024    2828186    2827853
4  2025    2871257    2871307
5  2026    2914061    2914504