In [ ]:
import pandas as pd

In [2]:
df = pd.read_excel(
    "Jumlah Penduduk Aceh.xlsx",
    sheet_name="Data 1",
    header=[1, 2]
)
display(df)
print("=="*20)
display(df.info())

   Unnamed: 0_level_0                                          Laki-Laki  \
   Unnamed: 0_level_1                                               2021
0            SIMEULUE                                              48230
1        ACEH SINGKIL                                              64926
2        ACEH SELATAN                                             117539
3       ACEH TENGGARA                                             112268
4          ACEH TIMUR                                             214498
5         ACEH TENGAH                                             110402
6          ACEH BARAT                                             101302
7          ACEH BESAR                                             206790
8               PIDIE                                             218324
9             BIREUEN                                             217751
10         ACEH UTARA                                             305524
11    ACEH BARAT DAYA                                              77117
12          GAYO LUES                                              50746
13       ACEH TAMIANG                                             150783
14         NAGAN RAYA                                              85804
15          ACEH JAYA                                              47876
16       BENER MERIAH                                              82844
17         PIDIE JAYA                                              79601
18         BANDA ACEH                                             128588
19             SABANG                                              21044
20             LANGSA                                              94511
21        LHOKSEUMAWE                                              94888
22       SUBULUSSALAM                                              46919
23      PROVINSI ACEH                                            2678275
24                NaN                                                NaN
25            Catatan  Sumber: <a style="color: #0093dd" href="https:...

                                                           Perempuan  \
         2022       2023       2024       2025       2026       2021
0     49014.0    49780.0    50550.0    51313.0    52055.0    45842.0
1     66151.0    67362.0    68573.0    69766.0    70950.0    63506.0
2    118863.0   120187.0   121490.0   122766.0   124009.0   116841.0
3    114178.0   116058.0   117905.0   119721.0   121502.0   111405.0
4    217351.0   220158.0   222928.0   225654.0   228322.0   212390.0
5    111905.0   113388.0   114842.0   116271.0   117672.0   107506.0
6    102388.0   103441.0   104454.0   105427.0   106369.0    99143.0
7    209881.0   212905.0   215873.0   218782.0   221637.0   203532.0
8    220782.0   223208.0   225588.0   227933.0   230226.0   220652.0
9    220930.0   224053.0   227111.0   230093.0   233007.0   223524.0
10   309204.0   312824.0   316382.0   319875.0   323291.0   304904.0
11    78256.0    79385.0    80494.0    81579.0    82646.0    75400.0
12    51717.0    52672.0    53627.0    54561.0    55492.0    50288.0
13   152770.0   154724.0   156646.0   158535.0   160389.0   146633.0
14    86857.0    87897.0    88904.0    89883.0    90833.0    84251.0
15    48696.0    49486.0    50268.0    51037.0    51780.0    46554.0
16    84301.0    85754.0    87187.0    88596.0    90001.0    80647.0
17    80740.0    81871.0    82976.0    84068.0    85134.0    80461.0
18   130150.0   131651.0   133079.0   134451.0   135758.0   126907.0
19    21329.0    21609.0    21877.0    22133.0    22390.0    20630.0
20    96051.0    97579.0    99096.0   100593.0   102084.0    93828.0
21    96465.0    98033.0    99566.0   101079.0   102573.0    96249.0
22    48041.0    49151.0    50275.0    51396.0    52517.0    45529.0
23  2716020.0  2753176.0  2789691.0  2825512.0  2860637.0  2656622.0
24        NaN        NaN        NaN        NaN        NaN        NaN
25        NaN        NaN        NaN        NaN        NaN        NaN

                                                           \
         2022       2023       2024       2025       2026
0     46586.0    47338.0    48083.0    48823.0    49549.0
1     64716.0    65912.0    67111.0    68304.0    69482.0
2    118068.0   119288.0   120504.0   121706.0   122892.0
3    113125.0   114832.0   116525.0   118189.0   119826.0
4    215192.0   217968.0   220710.0   223426.0   226109.0
5    108981.0   110445.0   111902.0   113337.0   114753.0
6    100248.0   101327.0   102368.0   103385.0   104369.0
7    206520.0   209468.0   212381.0   215260.0   218116.0
8    222773.0   224877.0   226959.0   229009.0   231028.0
9    226380.0   229189.0   231962.0   234683.0   237351.0
10   308513.0   312075.0   315602.0   319082.0   322511.0
11    76506.0    77605.0    78693.0    79762.0    80818.0
12    51251.0    52212.0    53164.0    54111.0    55050.0
13   148574.0   150493.0   152393.0   154285.0   156145.0
14    85362.0    86450.0    87525.0    88577.0    89607.0
15    47359.0    48152.0    48932.0    49701.0    50462.0
16    82056.0    83460.0    84849.0    86228.0    87599.0
17    81480.0    82490.0    83491.0    84478.0    85446.0
18   128636.0   130318.0   131940.0   133511.0   135037.0
19    20960.0    21279.0    21593.0    21909.0    22220.0
20    95483.0    97151.0    98813.0   100465.0   102119.0
21    97790.0    99322.0   100837.0   102331.0   103821.0
22    46608.0    47700.0    48787.0    49886.0    50982.0
23  2693167.0  2729351.0  2765124.0  2800448.0  2835292.0
24        NaN        NaN        NaN        NaN        NaN
25        NaN        NaN        NaN        NaN        NaN

   Laki-Laki + Perempuan                                              \
                    2021       2022       2023       2024       2025
0                94072.0    95600.0    97118.0    98633.0   100136.0
1               128432.0   130867.0   133274.0   135684.0   138070.0
2               234380.0   236931.0   239475.0   241994.0   244472.0
3               223673.0   227303.0   230890.0   234430.0   237910.0
4               426888.0   432543.0   438126.0   443638.0   449080.0
5               217908.0   220886.0   223833.0   226744.0   229608.0
6               200445.0   202636.0   204768.0   206822.0   208812.0
7               410322.0   416401.0   422373.0   428254.0   434042.0
8               438976.0   443555.0   448085.0   452547.0   456942.0
9               441275.0   447310.0   453242.0   459073.0   464776.0
10              610428.0   617717.0   624899.0   631984.0   638957.0
11              152517.0   154762.0   156990.0   159187.0   161341.0
12              101034.0   102968.0   104884.0   106791.0   108672.0
13              297416.0   301344.0   305217.0   309039.0   312820.0
14              170055.0   172219.0   174347.0   176429.0   178460.0
15               94430.0    96055.0    97638.0    99200.0   100738.0
16              163491.0   166357.0   169214.0   172036.0   174824.0
17              160062.0   162220.0   164361.0   166467.0   168546.0
18              255495.0   258786.0   261969.0   265019.0   267962.0
19               41674.0    42289.0    42888.0    43470.0    44042.0
20              188339.0   191534.0   194730.0   197909.0   201058.0
21              191137.0   194255.0   197355.0   200403.0   203410.0
22               92448.0    94649.0    96851.0    99062.0   101282.0
23             5334897.0  5409187.0  5482527.0  5554815.0  5625960.0
24                   NaN        NaN        NaN        NaN        NaN
25                   NaN        NaN        NaN        NaN        NaN


         2026
0    101604.0
1    140432.0
2    246901.0
3    241328.0
4    454431.0
5    232425.0
6    210738.0
7    439753.0
8    461254.0
9    470358.0
10   645802.0
11   163464.0
12   110542.0
13   316534.0
14   180440.0
15   102242.0
16   177600.0
17   170580.0
18   270795.0
19    44610.0
20   204203.0
21   206394.0
22   103499.0
23  5695929.0
24        NaN
25        NaN

========================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 19 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   (Unnamed: 0_level_0, Unnamed: 0_level_1)  25 non-null     object
 1   (Laki-Laki, 2021)                         25 non-null     object
 2   (Laki-Laki, 2022)                         24 non-null     float64
 3   (Laki-Laki, 2023)                         24 non-null     float64
 4   (Laki-Laki, 2024)                         24 non-null     float64
 5   (Laki-Laki, 2025)                         24 non-null     float64
 6   (Laki-Laki, 2026)                         24 non-null     float64
 7   (Perempuan, 2021)                         24 non-null     float64
 8   (Perempuan, 2022)                         24 non-null     float64
 9   (Perempuan, 2023)                         24 non-null     float64
 10  (Perempuan, 2024)                         24 non-null     float64
 11  (Perempuan, 2025)                         24 non-null     float64
 12  (Perempuan, 2026)                         24 non-null     float64
 13  (Laki-Laki + Perempuan, 2021)             24 non-null     float64
 14  (Laki-Laki + Perempuan, 2022)             24 non-null     float64
 15  (Laki-Laki + Perempuan, 2023)             24 non-null     float64
 16  (Laki-Laki + Perempuan, 2024)             24 non-null     float64
 17  (Laki-Laki + Perempuan, 2025)             24 non-null     float64
 18  (Laki-Laki + Perempuan, 2026)             24 non-null     float64
dtypes: float64(17), object(2)
memory usage: 4.0+ KB

None

In [3]:
df = df.drop(columns=['Laki-Laki + Perempuan'])

df.drop(index=[23,24,25], inplace=True)
display(df)

C:\Users\Adrian Alfarisi\AppData\Local\Temp\ipykernel_10224\2773902039.py:1: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  df = df.drop(columns=['Laki-Laki + Perempuan'])

   Unnamed: 0_level_0 Laki-Laki                                          \
   Unnamed: 0_level_1      2021      2022      2023      2024      2025
0            SIMEULUE     48230   49014.0   49780.0   50550.0   51313.0
1        ACEH SINGKIL     64926   66151.0   67362.0   68573.0   69766.0
2        ACEH SELATAN    117539  118863.0  120187.0  121490.0  122766.0
3       ACEH TENGGARA    112268  114178.0  116058.0  117905.0  119721.0
4          ACEH TIMUR    214498  217351.0  220158.0  222928.0  225654.0
5         ACEH TENGAH    110402  111905.0  113388.0  114842.0  116271.0
6          ACEH BARAT    101302  102388.0  103441.0  104454.0  105427.0
7          ACEH BESAR    206790  209881.0  212905.0  215873.0  218782.0
8               PIDIE    218324  220782.0  223208.0  225588.0  227933.0
9             BIREUEN    217751  220930.0  224053.0  227111.0  230093.0
10         ACEH UTARA    305524  309204.0  312824.0  316382.0  319875.0
11    ACEH BARAT DAYA     77117   78256.0   79385.0   80494.0   81579.0
12          GAYO LUES     50746   51717.0   52672.0   53627.0   54561.0
13       ACEH TAMIANG    150783  152770.0  154724.0  156646.0  158535.0
14         NAGAN RAYA     85804   86857.0   87897.0   88904.0   89883.0
15          ACEH JAYA     47876   48696.0   49486.0   50268.0   51037.0
16       BENER MERIAH     82844   84301.0   85754.0   87187.0   88596.0
17         PIDIE JAYA     79601   80740.0   81871.0   82976.0   84068.0
18         BANDA ACEH    128588  130150.0  131651.0  133079.0  134451.0
19             SABANG     21044   21329.0   21609.0   21877.0   22133.0
20             LANGSA     94511   96051.0   97579.0   99096.0  100593.0
21        LHOKSEUMAWE     94888   96465.0   98033.0   99566.0  101079.0
22       SUBULUSSALAM     46919   48041.0   49151.0   50275.0   51396.0

             Perempuan
        2026      2021      2022      2023      2024      2025      2026
0    52055.0   45842.0   46586.0   47338.0   48083.0   48823.0   49549.0
1    70950.0   63506.0   64716.0   65912.0   67111.0   68304.0   69482.0
2   124009.0  116841.0  118068.0  119288.0  120504.0  121706.0  122892.0
3   121502.0  111405.0  113125.0  114832.0  116525.0  118189.0  119826.0
4   228322.0  212390.0  215192.0  217968.0  220710.0  223426.0  226109.0
5   117672.0  107506.0  108981.0  110445.0  111902.0  113337.0  114753.0
6   106369.0   99143.0  100248.0  101327.0  102368.0  103385.0  104369.0
7   221637.0  203532.0  206520.0  209468.0  212381.0  215260.0  218116.0
8   230226.0  220652.0  222773.0  224877.0  226959.0  229009.0  231028.0
9   233007.0  223524.0  226380.0  229189.0  231962.0  234683.0  237351.0
10  323291.0  304904.0  308513.0  312075.0  315602.0  319082.0  322511.0
11   82646.0   75400.0   76506.0   77605.0   78693.0   79762.0   80818.0
12   55492.0   50288.0   51251.0   52212.0   53164.0   54111.0   55050.0
13  160389.0  146633.0  148574.0  150493.0  152393.0  154285.0  156145.0
14   90833.0   84251.0   85362.0   86450.0   87525.0   88577.0   89607.0
15   51780.0   46554.0   47359.0   48152.0   48932.0   49701.0   50462.0
16   90001.0   80647.0   82056.0   83460.0   84849.0   86228.0   87599.0
17   85134.0   80461.0   81480.0   82490.0   83491.0   84478.0   85446.0
18  135758.0  126907.0  128636.0  130318.0  131940.0  133511.0  135037.0
19   22390.0   20630.0   20960.0   21279.0   21593.0   21909.0   22220.0
20  102084.0   93828.0   95483.0   97151.0   98813.0  100465.0  102119.0
21  102573.0   96249.0   97790.0   99322.0  100837.0  102331.0  103821.0
22   52517.0   45529.0   46608.0   47700.0   48787.0   49886.0   50982.0

In [4]:
df.columns = [
    "Kabupaten/Kota" if "Unnamed" in str(col[0])
    else f"{col[0]}_{col[1]}"
    for col in df.columns
]

df = df.loc[:, ~df.columns.str.contains("Unnamed")]
display(df)

,Kabupaten/Kota,Laki-Laki_2021,Laki-Laki_2022,Laki-Laki_2023,Laki-Laki_2024,Laki-Laki_2025,Laki-Laki_2026,Perempuan_2021,Perempuan_2022,Perempuan_2023,Perempuan_2024,Perempuan_2025,Perempuan_2026
0,SIMEULUE,48230,49014.0,49780.0,50550.0,51313.0,52055.0,45842.0,46586.0,47338.0,48083.0,48823.0,49549.0
1,ACEH SINGKIL,64926,66151.0,67362.0,68573.0,69766.0,70950.0,63506.0,64716.0,65912.0,67111.0,68304.0,69482.0
2,ACEH SELATAN,117539,118863.0,120187.0,121490.0,122766.0,124009.0,116841.0,118068.0,119288.0,120504.0,121706.0,122892.0
3,ACEH TENGGARA,112268,114178.0,116058.0,117905.0,119721.0,121502.0,111405.0,113125.0,114832.0,116525.0,118189.0,119826.0
4,ACEH TIMUR,214498,217351.0,220158.0,222928.0,225654.0,228322.0,212390.0,215192.0,217968.0,220710.0,223426.0,226109.0
5,ACEH TENGAH,110402,111905.0,113388.0,114842.0,116271.0,117672.0,107506.0,108981.0,110445.0,111902.0,113337.0,114753.0
6,ACEH BARAT,101302,102388.0,103441.0,104454.0,105427.0,106369.0,99143.0,100248.0,101327.0,102368.0,103385.0,104369.0
7,ACEH BESAR,206790,209881.0,212905.0,215873.0,218782.0,221637.0,203532.0,206520.0,209468.0,212381.0,215260.0,218116.0
8,PIDIE,218324,220782.0,223208.0,225588.0,227933.0,230226.0,220652.0,222773.0,224877.0,226959.0,229009.0,231028.0
9,BIREUEN,217751,220930.0,224053.0,227111.0,230093.0,233007.0,223524.0,226380.0,229189.0,231962.0,234683.0,237351.0
10,ACEH UTARA,305524,309204.0,312824.0,316382.0,319875.0,323291.0,304904.0,308513.0,312075.0,315602.0,319082.0,322511.0
11,ACEH BARAT DAYA,77117,78256.0,79385.0,80494.0,81579.0,82646.0,75400.0,76506.0,77605.0,78693.0,79762.0,80818.0
12,GAYO LUES,50746,51717.0,52672.0,53627.0,54561.0,55492.0,50288.0,51251.0,52212.0,53164.0,54111.0,55050.0
13,ACEH TAMIANG,150783,152770.0,154724.0,156646.0,158535.0,160389.0,146633.0,148574.0,150493.0,152393.0,154285.0,156145.0
14,NAGAN RAYA,85804,86857.0,87897.0,88904.0,89883.0,90833.0,84251.0,85362.0,86450.0,87525.0,88577.0,89607.0
15,ACEH JAYA,47876,48696.0,49486.0,50268.0,51037.0,51780.0,46554.0,47359.0,48152.0,48932.0,49701.0,50462.0
16,BENER MERIAH,82844,84301.0,85754.0,87187.0,88596.0,90001.0,80647.0,82056.0,83460.0,84849.0,86228.0,87599.0
17,PIDIE JAYA,79601,80740.0,81871.0,82976.0,84068.0,85134.0,80461.0,81480.0,82490.0,83491.0,84478.0,85446.0
18,BANDA ACEH,128588,130150.0,131651.0,133079.0,134451.0,135758.0,126907.0,128636.0,130318.0,131940.0,133511.0,135037.0
19,SABANG,21044,21329.0,21609.0,21877.0,22133.0,22390.0,20630.0,20960.0,21279.0,21593.0,21909.0,22220.0
20,LANGSA,94511,96051.0,97579.0,99096.0,100593.0,102084.0,93828.0,95483.0,97151.0,98813.0,100465.0,102119.0
21,LHOKSEUMAWE,94888,96465.0,98033.0,99566.0,101079.0,102573.0,96249.0,97790.0,99322.0,100837.0,102331.0,103821.0
22,SUBULUSSALAM,46919,48041.0,49151.0,50275.0,51396.0,52517.0,45529.0,46608.0,47700.0,48787.0,49886.0,50982.0

In [7]:
df_umur = df.iloc[0:23]
total_laki = df_umur.iloc[:, 1:7].sum().values
total_perempuan = df_umur.iloc[:, 7:13].sum().values
df_ringkasan = pd.DataFrame({
    'Tahun': ['2021', '2022', '2023', '2024', '2025', '2026'],
    'Laki-Laki': total_laki,
    'Perempuan': total_perempuan
})

display(df_ringkasan)
df_ringkasan.to_csv('Jumlah Penduduk Aceh.csv', index=False)

  Tahun  Laki-Laki  Perempuan
0  2021    2678275  2656622.0
1  2022  2716020.0  2693167.0
2  2023  2753176.0  2729351.0
3  2024  2789691.0  2765124.0
4  2025  2825512.0  2800448.0
5  2026  2860637.0  2835292.0